### PR TITLE
fix: Support for LF & CRLF for better csv reading/mapping

### PR DESCRIPTION
**Pull request by m4tt72**
Added support for LF & CRLF for better csv reading/mapping
Remove last line from the csv if it was empty

### CODE REVIEW

**Comment by mikehardy** [comment]
looks good to me and broadens support even further, nice. 

Travis is chewing through it but appears on the way to 100% green - I’ll approve now then do you want to merge + release or do you want me to? I see Morocco on your profile I imagine it’s getting late there? Whatever you like. Seems like a patch release (1.5.1) based on semver?

**Comment by m4tt72** [comment]
Yeah it is getting late here 😅 just feel free to merge and bump the version!

**Comment by mikehardy** [comment]
Hey @m4tt72 I’m not sure what precisely happened with the 1.5.0 release when the `npm run shipit` failed on you, but the tag and the actual commit hash wasn’t in any tree I could find, so I found the hash that I could find with the 1.5.0 package.json update, rebased master on to it and moved the v1.5.0 tag on to it so the history was consistent on master

Which is to say that your local repository (and the fluicity fork) are very likely out of date now vs re-written history and you may need to clean them and re-clone, where “may need to” is “I’m almost sure you need to”. since the history and the tag are now different.

That’s not something I did lightly as playing with history on master is frowned-upon but since it’s only the two of us active right now I thought it best to get the history clean now before we got too much farther

**Comment by m4tt72** [comment]
Before committing or pushing I made sure I cloned this repo directly! So my last commits were on a clean repo... I'm not sure what happened... Did you resolve the issue?

**Comment by mikehardy** [comment]
Yeah - I resolved it - this PR was clean but that might explain it, the 1.5.0 tag and commit were lost along the way I guess? I'm not bothered but just want to make sure that after my force-push on to master you re-clone to make sure. It's all solved in the repo now, just maybe not in your checkout since I rewrote

**Pull request merged**
