### PR TITLE
feat: handle kotlin files

### PR DESCRIPTION
**Pull request by rozPierog**
Hey @mikehardy great work with combining all solutions into all in one package! I've added kotlin extension to jetify haven't really got time to check if this will work. I would love if you could check if I haven't broke anything. If you don't have time I'll do it around thursday.

### CODE REVIEW

**Comment by mikehardy** [comment]
I unfortunately have literally zero kotlin in my life :-), I think we have time though - let me know how it goes when you get a chance but at a glance it certainly seems simple enough and looks good

**Comment by mikehardy** [comment]
Hey @rozPierog I have a test rig now in https://github.com/mikehardy/rn-androidx-demo/ - if you can name one react-native extension that uses kotlin, I could integrate it into rn-androidx-demo, then test this, and merge it. I'm sure it's correct so should be a quick check

**Comment by rozPierog** [comment]
@mikehardy I've created simple prompt package just for this test https://www.npmjs.com/package/rn-android-prompt

**Comment by mikehardy** [comment]
Sweet! thank you - I made you a collaborator on the demo repo [just in case](https://en.wikipedia.org/wiki/Bus_factor), but I'll add this now to check and then merge

**Pull request merged**
